django_app_practies/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'django_app_practies.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),

                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^dashboard/', include('form_ex.urls')),
                       url(r'^sb_admin/', include('sb_admin.urls', namespace='sb_admin')),
                       url(r'^$', include('sb_admin.urls', namespace='sb_admin')),

                       url(r'^bootstrap/', include('form_ex.urls', namespace='bootstrap')),
                       url(r'^polls/', include('basic_site.urls', namespace="polls")),
                       url(r'^generic_view/', include('viewgeneration.urls', namespace="generic_view")),
                       url(r'^url/', include('basic_url.urls', namespace="basic_url")),
                       url(r'^basic_view/', include('basic_view.urls', namespace='basic_view')),
                       url(r'^form/', include('generic_editing_view.urls',
                                                              namespace='generic_editing_view')),

                       url(r'^async/', include('async_app.urls',
                                               namespace='async_view')),

                       url(r'effective_django/', include('effective_django_app.urls',
                                                         namespace='effective_django')),
                       )

# Overwrite handler 404 page
handler404 = 'basic_view.views.handler_404'

form_ex/urls.py
from django.conf.urls import patterns, url
from generic_editing_view import views
from form_ex import views

urlpatterns = patterns('',
                       url(r'(?P<page_name>\w+)/$',views.get_boot_strap_page, name='boot_strap'),
                       url(r'^$', views.load_dash_board),



)

sb_admin/urls.py
from django.conf.urls import patterns, url
from sb_admin import views

urlpatterns = patterns('',
                       url(r'^$', views.load_sb_dash_board, name='sb_admin'),
                       url(r'^pages/(?P<page_name>[\w\-]+)/$', views.load_page, name='load_page'),
                       url(r'^mypages/(?P<page_name>[\w\-]+)/$', views.load_my_page, name='load_my_page'),
                       url(r'^index/$', views.ArticleListView.as_view(), name='index'),
                       url(r'^create/$', views.ArticleCreate.as_view(), name='article_create'),

                       url(r'^detail/(?P<pk>\d+)/$', views.ArticleDetailView.as_view(), name='article_detail'),
                       url(r'^update/(?P<pk>\d+)/$', views.ArticleUpdate.as_view(), name='article_update'),
                       url(r'^delete/(?P<pk>\d+)/$', views.ArticleDelete.as_view(), name='article_delete'),


                       )

form_ex/forms.py
__author__ = 'root'

from django import forms
from sb_admin.models import Options
from django.forms.extras.widgets import SelectDateWidget
BIRTH_YEAR_CHOICES = ('1980', '1981', '1982')
FAVORITE_COLORS_CHOICES = (
    ('blue', 'Blue'),
    ('green', 'Green'),
    ('black', 'Black'),
)

CHOICES = (('1', 'First',), ('2', 'Second',))

class CommentForm(forms.Form):
    char_field = forms.CharField(max_length=100,
                                 widget=forms.TextInput())

    text_area = forms.CharField(max_length=100,
                                 widget=forms.Textarea())

    url = forms.URLField(widget=forms.URLInput())

    email = forms.EmailField(widget=forms.EmailInput())

    bool_field = forms.BooleanField(widget=forms.CheckboxInput(), required=True, label='Active')

    # Choice input data
    choice = forms.ChoiceField(widget=forms.RadioSelect(), choices=CHOICES)

    # Multiple check input
    multi_checkbox = forms.MultipleChoiceField(required=False, widget=forms.CheckboxSelectMultiple(), choices=FAVORITE_COLORS_CHOICES)



    # Select list from statis list
    select_from_static = forms.ChoiceField(widget=forms.Select(), choices=CHOICES)

    # Select options from database
    select_from_db = forms.ChoiceField(label='select  options fr db', choices=(),
                                       widget=forms.Select())
    # Multiple select from database
    multi_select = forms.MultipleChoiceField(widget=forms.SelectMultiple(),
                                           choices=FAVORITE_COLORS_CHOICES)


    multi_select_from_db = forms.ModelMultipleChoiceField(queryset=Options.objects.all(),
                                                          widget=forms.SelectMultiple())




class LoginForm(forms.Form):
    username = forms.CharField(max_length=100, label='UserName', label_suffix=': ',
                               widget=forms.TextInput())

    password = forms.CharField(max_length=100, label='Password', label_suffix=': ',
                               widget=forms.PasswordInput())

    comment = forms.CharField(widget=forms.Textarea())
    multi_choice = forms.MultipleChoiceField(required=False, widget=forms.CheckboxSelectMultiple(),
                                             choices=FAVORITE_COLORS_CHOICES, label='Multi Choise Demo')



    checkbox = forms.CheckboxInput()

templates/sb-admin/pages/mypages/article_delete_form.html
{% extends 'sb-admin/pages/base.html' %}
{% load bootstrap %}
{% block content %}
    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Forms</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Article Form
                    </div>
                    <div class="panel-body">
                        <div class="row">


                            <div class="col-lg-6">

                                <form action="" method="post"> {% csrf_token %}
                                    <p>Are you sure you want to delete {{ article.pub_date}}</p>
                                    <input type="submit" value="Delete Author" class="btn btn-primary"/>
                                    <a href="{% url 'sb_admin:index' %}" class="btn btn-primary">Cancel</a>
                                </form>

                            </div>


                            {% comment %}

                            <div class="col-lg-6">
                                <form class="form-horizontal" method="post">
                                    <legend>Form Title</legend>
                                    {% csrf_token %}
                                    {{ form|bootstrap_horizontal }}
                                    <div class="form-group">
                                        <div class="col-sm-10 col-sm-offset-2">
                                            <button type="submit" class="btn btn-primary">Submit</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                            {% endcomment %}

                            {% comment %}
                            <div class="col-lg-6">
                                <form class="form-inline">
                                    <legend>Form Title</legend>
                                    {% csrf_token %}
                                    {{ form|bootstrap_inline }}
                                    <div class="form-group">
                                        <div class="col-sm-10 col-sm-offset-2">
                                            <button type="submit" class="btn btn-primary">Submit</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                            {% endcomment %}


                            {% comment %}
                            <!-- /.col-lg-6 (nested) -->
                            <div class="col-lg-6">
                                <h1>Disabled Form States</h1>

                                <form role="form">
                                    <fieldset disabled>
                                        <div class="form-group">
                                            <label for="disabledSelect">Disabled input</label>
                                            <input class="form-control" id="disabledInput" type="text"
                                                   placeholder="Disabled input" disabled>
                                        </div>
                                        <div class="form-group">
                                            <label for="disabledSelect">Disabled select menu</label>
                                            <select id="disabledSelect" class="form-control">
                                                <option>Disabled select</option>
                                            </select>
                                        </div>
                                        <div class="checkbox">
                                            <label>
                                                <input type="checkbox">Disabled Checkbox
                                            </label>
                                        </div>
                                        <button type="submit" class="btn btn-primary">Disabled Button</button>
                                    </fieldset>
                                </form>
                                <h1>Form Validation States</h1>

                                <form role="form">
                                    <div class="form-group has-success">
                                        <label class="control-label" for="inputSuccess">Input with success</label>
                                        <input type="text" class="form-control" id="inputSuccess">
                                    </div>
                                    <div class="form-group has-warning">
                                        <label class="control-label" for="inputWarning">Input with warning</label>
                                        <input type="text" class="form-control" id="inputWarning">
                                    </div>
                                    <div class="form-group has-error">
                                        <label class="control-label" for="inputError">Input with error</label>
                                        <input type="text" class="form-control" id="inputError">
                                    </div>
                                </form>
                                <h1>Input Groups</h1>

                                <form role="form">
                                    <div class="form-group input-group">
                                        <span class="input-group-addon">@</span>
                                        <input type="text" class="form-control" placeholder="Username">
                                    </div>
                                    <div class="form-group input-group">
                                        <input type="text" class="form-control">
                                        <span class="input-group-addon">.00</span>
                                    </div>
                                    <div class="form-group input-group">
                                            <span class="input-group-addon"><i class="fa fa-eur"></i>
                                            </span>
                                        <input type="text" class="form-control" placeholder="Font Awesome Icon">
                                    </div>
                                    <div class="form-group input-group">
                                        <span class="input-group-addon">$</span>
                                        <input type="text" class="form-control">
                                        <span class="input-group-addon">.00</span>
                                    </div>
                                    <div class="form-group input-group">
                                        <input type="text" class="form-control">
                                            <span class="input-group-btn">
                                                <button class="btn btn-default" type="button"><i
                                                        class="fa fa-search"></i>
                                                </button>
                                            </span>
                                    </div>
                                </form>
                            </div>
                            <!-- /.col-lg-6 (nested) -->

                            {% endcomment %}
                        </div>
                        <!-- /.row (nested) -->
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /#page-wrapper -->


{% endblock content %}

templates/sb-admin/pages/mypages/article_list.html
{% extends 'sb-admin/pages/base.html' %}

{% block staticfile_web %}
    {{ block.super }}
    {% load staticfiles %}
    <!-- DataTables JavaScript -->
    <script src="{% static 'sb-admin/bower_components/datatables/media/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'sb-admin/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js' %}"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
        $(document).ready(function () {
            $('#dataTables-example').DataTable({
                responsive: true
            });
        });
    </script>
{% endblock staticfile_web %}

{% block title %}
    Article List
{% endblock title %}


{% block content %}
    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Tables</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Article Advanced Tables
                         <a href="{% url 'sb_admin:article_create' %}" class="btn btn-primary">Create new Article</a>


                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div class="dataTable_wrapper">
                            <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                <thead>
                                <tr>
                                    <th>Pub Date</th>
                                    <th>Headline </th>
                                    <th>Content</th>
                                    <th>Reporter</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% if article_list %}
                                    <ul>
                                        {% for article in article_list %}
                                            <tr class="odd gradeX">
                                                <td>{{ article.pub_date }}</td>
                                                <td>{{ article.headline }}</td>
                                                <td>{{ article.content }}</td>
                                                <td class="center">{{ article.reporter }}</td>
                                                <td class="center"><a href="{% url 'sb_admin:article_update' article.pk%}"><span class="glyphicon glyphicon-edit"> Edit </span></a></td>
                                                <td class="center"><a href="{% url 'sb_admin:article_delete' article.pk%}"><span class="glyphicon glyphicon-remove-sign"> Delete </span></a></td>
                                            </tr>
                                        {% endfor %}
                                    </ul>
                                {% else %}
                                    <p>Do not have any Article</p>
                                {% endif %}

                                </tbody>
                            </table>
                        </div>

                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->

        </div>
    </div>
    <!-- /#page-wrapper -->
{% endblock content %}

templates/sb-admin/pages/mypages/forms.html
{% extends 'sb-admin/pages/base.html' %}
{% block content %}
    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Forms</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Basic Form Elements
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-6">
                                <form action="{% url 'sb_admin:load_my_page' 'forms' %}" method="post" role="form">
                                    {% csrf_token %}
                                    {{ form.as_table}}
                                    <input type="submit" value="Submit" class="btn btn-default"/>

                                </form>
                            </div>

                            {% comment %}
                            <!-- /.col-lg-6 (nested) -->
                            <div class="col-lg-6">
                                <h1>Disabled Form States</h1>

                                <form role="form">
                                    <fieldset disabled>
                                        <div class="form-group">
                                            <label for="disabledSelect">Disabled input</label>
                                            <input class="form-control" id="disabledInput" type="text"
                                                   placeholder="Disabled input" disabled>
                                        </div>
                                        <div class="form-group">
                                            <label for="disabledSelect">Disabled select menu</label>
                                            <select id="disabledSelect" class="form-control">
                                                <option>Disabled select</option>
                                            </select>
                                        </div>
                                        <div class="checkbox">
                                            <label>
                                                <input type="checkbox">Disabled Checkbox
                                            </label>
                                        </div>
                                        <button type="submit" class="btn btn-primary">Disabled Button</button>
                                    </fieldset>
                                </form>
                                <h1>Form Validation States</h1>

                                <form role="form">
                                    <div class="form-group has-success">
                                        <label class="control-label" for="inputSuccess">Input with success</label>
                                        <input type="text" class="form-control" id="inputSuccess">
                                    </div>
                                    <div class="form-group has-warning">
                                        <label class="control-label" for="inputWarning">Input with warning</label>
                                        <input type="text" class="form-control" id="inputWarning">
                                    </div>
                                    <div class="form-group has-error">
                                        <label class="control-label" for="inputError">Input with error</label>
                                        <input type="text" class="form-control" id="inputError">
                                    </div>
                                </form>
                                <h1>Input Groups</h1>

                                <form role="form">
                                    <div class="form-group input-group">
                                        <span class="input-group-addon">@</span>
                                        <input type="text" class="form-control" placeholder="Username">
                                    </div>
                                    <div class="form-group input-group">
                                        <input type="text" class="form-control">
                                        <span class="input-group-addon">.00</span>
                                    </div>
                                    <div class="form-group input-group">
                                            <span class="input-group-addon"><i class="fa fa-eur"></i>
                                            </span>
                                        <input type="text" class="form-control" placeholder="Font Awesome Icon">
                                    </div>
                                    <div class="form-group input-group">
                                        <span class="input-group-addon">$</span>
                                        <input type="text" class="form-control">
                                        <span class="input-group-addon">.00</span>
                                    </div>
                                    <div class="form-group input-group">
                                        <input type="text" class="form-control">
                                            <span class="input-group-btn">
                                                <button class="btn btn-default" type="button"><i
                                                        class="fa fa-search"></i>
                                                </button>
                                            </span>
                                    </div>
                                </form>
                            </div>
                            <!-- /.col-lg-6 (nested) -->

                            {% endcomment %}
                        </div>
                        <!-- /.row (nested) -->
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /#page-wrapper -->


{% endblock content %}

templates/sb-admin/pages/mypages/panels-wells.html
{% extends 'sb-admin/pages/base.html' %}
{% block content %}
    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">REMOTE CONTROL WEBSERVER</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>


    <ul class="nav nav-pills">
    <li class="active"><a data-toggle="tab" href="#menu1">Control Panel</a></li>
    <li><a data-toggle="tab" href="#menu2">Temperature</a></li>
    <li><a data-toggle="tab" href="#menu3">Camera</a></li>
  </ul>

  <div class="tab-content">
    <div id="home" class="tab-pane fade in active">
      <h3>HOME</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </div>
    <div id="menu1" class="tab-pane fade">
      <h3>Menu 1</h3>
      <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    </div>
    <div id="menu2" class="tab-pane fade">
      <h3>Menu 2</h3>
      <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
    </div>
    <div id="menu3" class="tab-pane fade">
      <h3>Menu 3</h3>
      <p>Eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
    </div>
  </div>


    </div>
    <!-- /#page-wrapper -->
{% endblock content %}

templates/sb-admin/pages/mypages/test.html
<form action="/sb_admin/mypages/forms/" method="post" role="form">
    <input type='hidden' name='csrfmiddlewaretoken' value='ui7r67cmDlsmkZx3rnCFBqpOHW7dwsWp'/>
    <tr>
        <th><label for="id_char_field">Char field:</label></th>
        <td><input class="form-control" id="id_char_field" maxlength="100" name="char_field" placeholder="Enter here"
                   type="text"/></td>
    </tr>
    <tr>
        <th><label for="id_text_area">Text area:</label></th>
        <td><textarea class="form-control" cols="40" id="id_text_area" maxlength="100" name="text_area"
                      placeholder="Enter here" rows="10">
</textarea></td>
    </tr>
    <tr>
        <th><label for="id_url">Url:</label></th>
        <td><input class="form-control" id="id_url" name="url" placeholder="Enter your url" type="url"/></td>
    </tr>
    <tr>
        <th><label for="id_multi_select_0">Multi select:</label></th>
        <td>
            <ul id="id_multi_select">
                <li><label for="id_multi_select_0"><input id="id_multi_select_0" name="multi_select" type="checkbox"
                                                          value="1"/> lhs</label></li>
                <li><label for="id_multi_select_1"><input id="id_multi_select_1" name="multi_select" type="checkbox"
                                                          value="2"/> lylan</label></li>
                <li><label for="id_multi_select_2"><input id="id_multi_select_2" name="multi_select" type="checkbox"
                                                          value="3"/> abc</label></li>
                <li><label for="id_multi_select_3"><input id="id_multi_select_3" name="multi_select" type="checkbox"
                                                          value="4"/> xyz</label></li>
            </ul>
        </td>
    </tr>
    <tr>
        <th><label for="id_choice_0">Choice:</label></th>
        <td>
            <ul id="id_choice">
                <li><label for="id_choice_0"><input id="id_choice_0" name="choice" type="radio" value="1"/> lhs</label>
                </li>
                <li><label for="id_choice_1"><input id="id_choice_1" name="choice" type="radio" value="2"/>
                    lylan</label></li>
                <li><label for="id_choice_2"><input id="id_choice_2" name="choice" type="radio" value="3"/> abc</label>
                </li>
                <li><label for="id_choice_3"><input id="id_choice_3" name="choice" type="radio" value="4"/> xyz</label>
                </li>
            </ul>
        </td>
    </tr>
    <tr>
        <th><label for="id_select_from_static">Select from static:</label></th>
        <td><select class="form-control" id="id_select_from_static" name="select_from_static">
            <option value="1">First</option>
            <option value="2">Second</option>
        </select></td>
    </tr>
    <tr>
        <th><label for="id_select_from_db">select options fr db:</label></th>
        <td><select class="form-control" id="id_select_from_db" name="select_from_db">
            <option value="1">lhs</option>
            <option value="2">lylan</option>
            <option value="3">abc</option>
            <option value="4">xyz</option>
        </select></td>
    </tr>
    <input type="submit" value="Submit" class="btn btn-default"/>