django_app_practies/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'django_app_practies.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),

                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^dashboard/', include('form_ex.urls')),
                       url(r'^sb_admin/', include('sb_admin.urls', namespace='sb_admin')),
                       url(r'^$', include('sb_admin.urls', namespace='sb_admin')),

                       url(r'^bootstrap/', include('form_ex.urls', namespace='bootstrap')),
                       url(r'^polls/', include('basic_site.urls', namespace="polls")),
                       url(r'^generic_view/', include('viewgeneration.urls', namespace="generic_view")),
                       url(r'^url/', include('basic_url.urls', namespace="basic_url")),
                       url(r'^basic_view/', include('basic_view.urls', namespace='basic_view')),
                       url(r'^form/', include('generic_editing_view.urls',
                                                              namespace='generic_editing_view')),

                       url(r'^async/', include('async_app.urls',
                                               namespace='async_view')),

                       url(r'effective_django/', include('effective_django_app.urls',
                                                         namespace='effective_django')),
                       )

# Overwrite handler 404 page
handler404 = 'basic_view.views.handler_404'

form_ex/urls.py
from django.conf.urls import patterns, url
from generic_editing_view import views
from form_ex import views

urlpatterns = patterns('',
                       url(r'(?P<page_name>\w+)/$',views.get_boot_strap_page, name='boot_strap'),
                       url(r'^$', views.load_dash_board),



)

generic_editing_view/urls.py
from django.conf.urls import patterns, url
from generic_editing_view import views
from generic_editing_view.controller import user

urlpatterns = patterns('',
                       # Link to dasbhboard, include all practices
                       
                       url(r'^index/$', views.IndexAuthorView.as_view(), name='index'),
                       # url(r'^contact/$', views.ContactView.as_view(), name='contact'),
                       url(r'^contact/$', user.get_contact, name='contact'),
                       url(r'^thanks/$', views.load_thank_page, name='thanks'),
                       url(r'^create/$', views.AuthorCreate.as_view(), name='author_create'),
                       url(r'^detail/(?P<pk>\d+)/$', views.AuthorDetailView.as_view(), name='author_detail'),
                       url(r'^update/(?P<pk>\d+)/$', views.AuthorUpdate.as_view(), name='author_update'),
                       url(r'^delete/(?P<pk>\d+)/$', views.AuthorDelete.as_view(), name='author_delete'),

                       url(r'^name/$', user.get_name, name='name'),


)

generic_editing_view/models.py
from django.db import models
from django.core.urlresolvers import reverse


# Create your models here.
class Author(models.Model):
    name = models.CharField(max_length=200)

    def get_absolute_url(self):
        return reverse('generic_editing_view:author_detail', kwargs={'pk': self.pk})

generic_editing_view/forms.py
__author__ = 'root'
from django import forms
import logging
logger = logging.getLogger(__name__)


class ContactForm(forms.Form):
    name = forms.CharField(label='Author Name', max_length=100)
    message = forms.CharField(widget=forms.Textarea)

    def send_mail(self):
        # logger.debug('%s %s ' % (self.message, self.name))
        pass


class NameForm(forms.Form):
    your_name = forms.CharField(label='Your name', max_length=100)


class ContactFormEx(forms.Form):
    subject = forms.CharField(max_length=100, help_text='Max 100 characters')
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField(error_messages={'required': 'Please enter sender email', 'invalid': 'invalid email'})
    cc_myself = forms.BooleanField(required=False)

generic_editing_view/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView
from django.views import generic
from generic_editing_view.forms import ContactForm
from django.core.urlresolvers import reverse
from generic_editing_view.models import Author


def load_dash_board(request):
    return render(request, 'basic_view/base.html')


# Create your views here.
class ContactView(FormView):
    template_name = 'generic_editing_view/contact.html'
    form_class = ContactForm


    def get_success_url(self):
        return reverse('generic_editing_view:thanks')

    def form_valid(self, form):
        form.send_mail()
        return super(ContactView, self).form_valid(form)


def load_thank_page(request):
    return render(request, 'generic_editing_view/thank_page.html')

# Create Author
class AuthorCreate(CreateView):
    model = Author
    fields = ['name']
    template_name = 'generic_editing_view/author_form.html'


    def get_success_url(self):
        return reverse('generic_editing_view:index')


# Detail Author
class AuthorDetailView(generic.DetailView):
    model = Author
    context_object_name = 'author'
    template_name = 'generic_editing_view/author_detail_page.html'


# Update Form
class AuthorUpdate(UpdateView):
    model = Author
    fields = ['name']
    template_name = 'generic_editing_view/author_update_form.html'

    def get_success_url(self):
        return reverse('generic_editing_view:index')


# View Index List
class IndexAuthorView(generic.ListView):
    template_name = 'generic_editing_view/view_list.html'
    context_object_name = 'author_list'

    def get_queryset(self):
        return Author.objects.all()


# Delete Author
class AuthorDelete(DeleteView):
    model = Author
    #success_url = reverse('generic_editing_view:index', args=[])
    context_object_name = 'author'
    template_name = 'generic_editing_view/author_delete.html'

    def get_success_url(self):
        return reverse('generic_editing_view:index')

templates/generic_editing_view/author_delete.html
{% extends 'basic_view/base.html' %}
{% block title %}
    Delete Author
{% endblock title %}

{% block main_body %}
    <form action="" method="post"> {% csrf_token %}
        <p>Are you sure you want to delete {{ author.name }}</p>
        <input type="submit" value="Delete Author"/>
    </form>
{% endblock main_body %}

templates/generic_editing_view/author_detail_page.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<h3>Author Name: {{ author.name }}</h3>

</body>
</html>

templates/generic_editing_view/author_form.html
{% extends 'basic_view/base.html' %}
{% block title %}
Create New Author
{% endblock title %}

{% block main_body %}
<form action="" method="post"> {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create" />
</form>
{% endblock main_body %}

templates/generic_editing_view/author_update_form.html
{% extends 'basic_view/base.html' %}
{% block title %}
    Update Author
{% endblock title %}

{% block main_body %}
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update"/>

    </form>
{% endblock %}

templates/generic_editing_view/contact.html
{% extends "basic_view/base.html" %}
{% block main_body %}
    <form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send message">
</form>
{% endblock main_body %}

templates/generic_editing_view/thank_page.html
{% extends 'basic_view/base.html' %}
{% block title %}
    Thank you
{% endblock title %}

{% block main_body %}
    <h3>Thanks you to contact with us</h3>
{% endblock main_body %}

templates/generic_editing_view/view_list.html
{% extends 'basic_view/base.html' %}
{% block title %}
    Author List
{% endblock title %}

{% block main_body %}
    {% if author_list %}
        <ul>
            {% for author in author_list %}
                <li><a href="{% url 'generic_editing_view:author_update' author.pk %}"> Update {{ author.name }}</a>
                </li>
                <li><a href="{% url 'generic_editing_view:author_delete' author.pk %}"> Delete {{ author.name }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Do not have any author</p>
    {% endif %}

    <a href="{% url 'generic_editing_view:author_create'%}"> Create Author</a>
{% endblock main_body %}