django_app_practies/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'django_app_practies.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),

                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^dashboard/', include('form_ex.urls')),
                       url(r'^sb_admin/', include('sb_admin.urls', namespace='sb_admin')),
                       url(r'^$', include('sb_admin.urls', namespace='sb_admin')),

                       url(r'^bootstrap/', include('form_ex.urls', namespace='bootstrap')),
                       url(r'^polls/', include('basic_site.urls', namespace="polls")),
                       url(r'^generic_view/', include('viewgeneration.urls', namespace="generic_view")),
                       url(r'^url/', include('basic_url.urls', namespace="basic_url")),
                       url(r'^basic_view/', include('basic_view.urls', namespace='basic_view')),
                       url(r'^form/', include('generic_editing_view.urls',
                                                              namespace='generic_editing_view')),

                       url(r'^async/', include('async_app.urls',
                                               namespace='async_view')),

                       url(r'effective_django/', include('effective_django_app.urls',
                                                         namespace='effective_django')),
                       )

# Overwrite handler 404 page
handler404 = 'basic_view.views.handler_404'

form_ex/urls.py
from django.conf.urls import patterns, url
from generic_editing_view import views
from form_ex import views

urlpatterns = patterns('',
                       url(r'(?P<page_name>\w+)/$',views.get_boot_strap_page, name='boot_strap'),
                       url(r'^$', views.load_dash_board),



)

sb_admin/urls.py
from django.conf.urls import patterns, url
from sb_admin import views

urlpatterns = patterns('',
                       url(r'^$', views.load_sb_dash_board, name='sb_admin'),
                       url(r'^pages/(?P<page_name>[\w\-]+)/$', views.load_page, name='load_page'),
                       url(r'^mypages/(?P<page_name>[\w\-]+)/$', views.load_my_page, name='load_my_page'),
                       url(r'^index/$', views.ArticleListView.as_view(), name='index'),
                       url(r'^create/$', views.ArticleCreate.as_view(), name='article_create'),

                       url(r'^detail/(?P<pk>\d+)/$', views.ArticleDetailView.as_view(), name='article_detail'),
                       url(r'^update/(?P<pk>\d+)/$', views.ArticleUpdate.as_view(), name='article_update'),
                       url(r'^delete/(?P<pk>\d+)/$', views.ArticleDelete.as_view(), name='article_delete'),


                       )

templates/sb-admin/pages/includes/navbar_header.html
<div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{% url 'sb_admin:sb_admin' %}">SB Admin v2.0</a>
</div>
<!-- /.navbar-header -->

templates/sb-admin/pages/includes/navbar_right.html
    <ul class="nav navbar-top-links navbar-right">
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-envelope fa-fw"></i> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-messages">
                <li>
                    <a href="#">
                        <div>
                            <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                        </div>
                        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                        </div>
                        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                        </div>
                        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a class="text-center" href="#">
                        <strong>Read All Messages</strong>
                        <i class="fa fa-angle-right"></i>
                    </a>
                </li>
            </ul>
            <!-- /.dropdown-messages -->
        </li>
        <!-- /.dropdown -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-tasks fa-fw"></i> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-tasks">
                <li>
                    <a href="#">
                        <div>
                            <p>
                                <strong>Task 1</strong>
                                <span class="pull-right text-muted">40% Complete</span>
                            </p>

                            <div class="progress progress-striped active">
                                <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40"
                                     aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                                    <span class="sr-only">40% Complete (success)</span>
                                </div>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <p>
                                <strong>Task 2</strong>
                                <span class="pull-right text-muted">20% Complete</span>
                            </p>

                            <div class="progress progress-striped active">
                                <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20"
                                     aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                                    <span class="sr-only">20% Complete</span>
                                </div>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <p>
                                <strong>Task 3</strong>
                                <span class="pull-right text-muted">60% Complete</span>
                            </p>

                            <div class="progress progress-striped active">
                                <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60"
                                     aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                                    <span class="sr-only">60% Complete (warning)</span>
                                </div>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <p>
                                <strong>Task 4</strong>
                                <span class="pull-right text-muted">80% Complete</span>
                            </p>

                            <div class="progress progress-striped active">
                                <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80"
                                     aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                                    <span class="sr-only">80% Complete (danger)</span>
                                </div>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a class="text-center" href="#">
                        <strong>See All Tasks</strong>
                        <i class="fa fa-angle-right"></i>
                    </a>
                </li>
            </ul>
            <!-- /.dropdown-tasks -->
        </li>
        <!-- /.dropdown -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-bell fa-fw"></i> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-alerts">
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-comment fa-fw"></i> New Comment
                            <span class="pull-right text-muted small">4 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                            <span class="pull-right text-muted small">12 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-envelope fa-fw"></i> Message Sent
                            <span class="pull-right text-muted small">4 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-tasks fa-fw"></i> New Task
                            <span class="pull-right text-muted small">4 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-upload fa-fw"></i> Server Rebooted
                            <span class="pull-right text-muted small">4 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a class="text-center" href="#">
                        <strong>See All Alerts</strong>
                        <i class="fa fa-angle-right"></i>
                    </a>
                </li>
            </ul>
            <!-- /.dropdown-alerts -->
        </li>
        <!-- /.dropdown -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                </li>
                <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                </li>
                <li class="divider"></li>
                <li><a href="{% url 'sb_admin:load_page' 'login' %}"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                </li>
            </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->

templates/sb-admin/pages/includes/navbar_side.html
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li class="sidebar-search">
                <div class="input-group custom-search-form">
                    <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                </div>
                <!-- /input-group -->
            </li>
            <li>
                <a href="{% url 'sb_admin:load_page' 'index' %}"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Charts<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="{% url 'sb_admin:load_page' 'flot' %}">Flot Charts</a>
                    </li>
                    <li>
                        <a href="{% url 'sb_admin:load_page' 'morris' %}">Morris.js Charts</a>
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>
            <li>
                <a href="{% url 'sb_admin:load_page' 'tables' %}"><i class="fa fa-table fa-fw"></i> Tables</a>
            </li>
            <li>
                <a href="{% url 'sb_admin:load_page' 'forms' %}"><i class="fa fa-edit fa-fw"></i> Forms</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-wrench fa-fw"></i> UI Elements<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="{% url 'sb_admin:load_page' 'panels-wells' %}">Panels and Wells</a>
                    </li>
                    <li>
                        <a href="{% url 'sb_admin:load_page' 'buttons' %}">Buttons</a>
                    </li>
                    <li>
                        <a href="{% url 'sb_admin:load_page' 'notifications' %}">Notifications</a>
                    </li>
                    <li>
                        <a href="{% url 'sb_admin:load_page' 'typography' %}">Typography</a>
                    </li>
                    <li>
                        <a href="{% url 'sb_admin:load_page' 'icons' %}"> Icons</a>
                    </li>
                    <li>
                        <a href="{% url 'sb_admin:load_page' 'grid' %}">Grid</a>
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>
            <li>
                <a href="#"><i class="fa fa-sitemap fa-fw"></i> Multi-Level Dropdown<span
                        class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="#">Second Level Item</a>
                    </li>
                    <li>
                        <a href="#">Second Level Item</a>
                    </li>
                    <li>
                        <a href="#">Third Level <span class="fa arrow"></span></a>
                        <ul class="nav nav-third-level">
                            <li>
                                <a href="#">Third Level Item</a>
                            </li>
                            <li>
                                <a href="#">Third Level Item</a>
                            </li>
                            <li>
                                <a href="#">Third Level Item</a>
                            </li>
                            <li>
                                <a href="#">Third Level Item</a>
                            </li>
                        </ul>
                        <!-- /.nav-third-level -->
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>
            <li>
                <a href="#"><i class="fa fa-files-o fa-fw"></i> Sample Pages<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="{% url 'sb_admin:load_page' 'blank' %}">Blank Page</a>
                    </li>
                    <li>
                        <a href="{% url 'sb_admin:load_page' 'login' %}">Login Page</a>
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>

            <li>
                <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> My Practices<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="{% url 'sb_admin:load_my_page' 'tables' %}">Advance Table</a>
                    </li>
                    <li>
                        <a href="{% url 'sb_admin:load_my_page' 'forms' %}">My Form</a>
                    </li>
                    <li>
                        <a href="{% url 'sb_admin:load_my_page' 'form_bootstrap_3_5' %}">BootStrap</a>
                    </li>
                    <li>
                        <a href="{% url 'sb_admin:load_my_page' 'panels-wells' %}">My Panel-wells</a>
                    </li>

                    <li>
                        <a href="{% url 'sb_admin:load_my_page' 'bootstrapform' %}">BootStrap Form</a>
                    </li>
                    <li>
                        <a href="{% url 'sb_admin:load_my_page' 'article_form' %}">My Article Form </a>
                    </li>

                    <li>
                        <a href="{% url 'sb_admin:index'%}">Article List</a>
                    </li>

                </ul>
                <!-- /.nav-second-level -->
            </li>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>
<!-- /.navbar-static-side -->

templates/sb-admin/pages/includes/navigation.html
<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">

    {% include 'sb-admin/pages/includes/navbar_header.html' %}

    {% include 'sb-admin/pages/includes/navbar_right.html' %}

    {% include 'sb-admin/pages/includes/navbar_side.html' %}
</nav>