basic_view/urls.py
__author__ = 'root'
from django.conf.urls import patterns, url
from basic_view import views


urlpatterns = patterns('',
                       url(r'^$', views.get_template_page, name='template_page'),
                       url(r'^current_time/$', views.get_current_date_time_page, name='current_time_page'),
                       url(r'^include_page/$', views.get_include_page, name='include_page'),
)

django_app_practies/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'django_app_practies.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),

                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^dashboard/', include('form_ex.urls')),
                       url(r'^sb_admin/', include('sb_admin.urls', namespace='sb_admin')),
                       url(r'^$', include('sb_admin.urls', namespace='sb_admin')),

                       url(r'^bootstrap/', include('form_ex.urls', namespace='bootstrap')),
                       url(r'^polls/', include('basic_site.urls', namespace="polls")),
                       url(r'^generic_view/', include('viewgeneration.urls', namespace="generic_view")),
                       url(r'^url/', include('basic_url.urls', namespace="basic_url")),
                       url(r'^basic_view/', include('basic_view.urls', namespace='basic_view')),
                       url(r'^form/', include('generic_editing_view.urls',
                                                              namespace='generic_editing_view')),

                       url(r'^async/', include('async_app.urls',
                                               namespace='async_view')),

                       url(r'effective_django/', include('effective_django_app.urls',
                                                         namespace='effective_django')),
                       )

# Overwrite handler 404 page
handler404 = 'basic_view.views.handler_404'

form_ex/urls.py
from django.conf.urls import patterns, url
from generic_editing_view import views
from form_ex import views

urlpatterns = patterns('',
                       url(r'(?P<page_name>\w+)/$',views.get_boot_strap_page, name='boot_strap'),
                       url(r'^$', views.load_dash_board),



)

generic_editing_view/urls.py
from django.conf.urls import patterns, url
from generic_editing_view import views
from generic_editing_view.controller import user

urlpatterns = patterns('',
                       # Link to dasbhboard, include all practices
                       
                       url(r'^index/$', views.IndexAuthorView.as_view(), name='index'),
                       # url(r'^contact/$', views.ContactView.as_view(), name='contact'),
                       url(r'^contact/$', user.get_contact, name='contact'),
                       url(r'^thanks/$', views.load_thank_page, name='thanks'),
                       url(r'^create/$', views.AuthorCreate.as_view(), name='author_create'),
                       url(r'^detail/(?P<pk>\d+)/$', views.AuthorDetailView.as_view(), name='author_detail'),
                       url(r'^update/(?P<pk>\d+)/$', views.AuthorUpdate.as_view(), name='author_update'),
                       url(r'^delete/(?P<pk>\d+)/$', views.AuthorDelete.as_view(), name='author_delete'),

                       url(r'^name/$', user.get_name, name='name'),


)

sb_admin/urls.py
from django.conf.urls import patterns, url
from sb_admin import views

urlpatterns = patterns('',
                       url(r'^$', views.load_sb_dash_board, name='sb_admin'),
                       url(r'^pages/(?P<page_name>[\w\-]+)/$', views.load_page, name='load_page'),
                       url(r'^mypages/(?P<page_name>[\w\-]+)/$', views.load_my_page, name='load_my_page'),
                       url(r'^index/$', views.ArticleListView.as_view(), name='index'),
                       url(r'^create/$', views.ArticleCreate.as_view(), name='article_create'),

                       url(r'^detail/(?P<pk>\d+)/$', views.ArticleDetailView.as_view(), name='article_detail'),
                       url(r'^update/(?P<pk>\d+)/$', views.ArticleUpdate.as_view(), name='article_update'),
                       url(r'^delete/(?P<pk>\d+)/$', views.ArticleDelete.as_view(), name='article_delete'),


                       )

basic_view/models.py
from django.db import models

# Create your models here.

basic_view/views.py
from django.shortcuts import render
from django.views.decorators.http import require_http_methods
from datetime import datetime


# Create your views here.
'''
@require_http_methods(['GET'])
def get_page_home(request):
    return render(request, 'basic_view/home_page.html')
'''


def handler_404(request):
    return render(request, 'basic_view/404_page.html', status=404)

# Home page of directory /basic_view
# view root page same as base page in django admin template
def get_template_page(request):
    return render(request, 'basic_view/template.html')


# Inheritance template page, replace titile and content of base page
def get_current_date_time_page(request):
    return render(request, 'basic_view/current_datetime.html', {'current_date': datetime.now()})

#
def get_include_page(request):
    # return render(request, 'basic_view/base.html', {'header_part': 'basic_view/includes/header.html',
    #                                                         'footer_part': 'basic_view/includes/footer.html'})

    return render(request, 'basic_view/block_template.html')

templates/basic_view/includes/calendar_part.html
<script>
    $(document).ready(function () {
        $("#input_from_time").datepicker(
                {dateFormat: 'dd/mm/yy'}
        );

         $("#input_to_time").datepicker(
                {dateFormat: 'dd/mm/yy'}
        );
    });
</script>

<form action="" method="get">
    <input type="text" value="From Day" id="input_from_time"/>
    <input type="text" value="To Day" id="input_to_time"/>
    <input type="submit" value="View History"/>
</form>

templates/basic_view/includes/footer.html
<p>Footer part</p>

templates/basic_view/includes/header.html
<p>Header part</p>

templates/basic_view/includes/menu_part.html
<ul>
    <li>
        <a href="{% url 'generic_editing_view:index' %}">Home</a>
    </li>

    <li>
        <a href="#">Service</a>
    </li>

    <li>
        <a href="#">About</a>
    </li>


    <li>
        <a href="{% url 'generic_editing_view:name' %}">Name</a>
    </li>


    <li>
        <a href="{% url 'generic_editing_view:contact' %}">Contact</a>
    </li>




</ul>

templates/basic_view/includes/side_bar_part.html
<div class="dropdown">
    <button class="btn btn-default dropdown-toggle" type="button" id="menu1" data-toggle="dropdown">BootStrap Tutorial
        <span class="caret"></span></button>
    <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
        <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'bootstrap:boot_strap' 'button' %}">Button</a></li>
        <li role="presentation" class="divider"></li>
        <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'bootstrap:boot_strap' 'table' %}">Table</a></li>
        <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'bootstrap:boot_strap' 'form' %}">Form</a></li>
        <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'bootstrap:boot_strap' 'login' %}">Input Data</a></li>
        <li role="presentation"><a role="menuitem" tabindex="-1" href="#">CSS</a></li>
        <li role="presentation" class="divider"></li>
        <li role="presentation"><a role="menuitem" tabindex="-1" href="#">About Us</a></li>
    </ul>
</div>